function footerText() {
            const footers = [
        "in solidarity,",
        "from the river to the sea,",
        "with energy,",
        "i'm just happy to be here,",
        "hell if i know,",
        "or else,",
        "ingest immediately after reading,",
        "good luck final girl,",
        "inevitably,",
        "nothing more to say,",
        "sensitive but unclassified,",
        "asynchronously,",
        "collapsing into the ether,",
        "love and rage,",
        "i wish you nothing but joy,",
        "all's well that ends,",
        "stars aligning,",
        "to insanity,",
        "hand in unloveable hand,",
        "chronically,",
        "as above; so below,",
        "godspeed,",
        "bending towards the sun,",
        "i wish you a kinder internet,",
        "try me,",
        "strategically aligned,",
        "through gritted teeth,",
        "may it be unfamiliar, potentially threatening, and new,",
        "you'll never catch me alive,",
        "diabolically,",
        "sonically yours,",
        "painfully yours,",
        "handled with care,",
        "made with magic,",
        "the world is abundant,",
        "regrettably,",
        "just like we never said goodbye,",
        "by a show of hands,",
        "cheering for you from afar,",
        "with reasonable love,",
        "everything eats and is eaten,",
        "your brother in christ,",
        "and that's on god,",
        "trust the process,",
        "tomorrow, and tomorrow, and tomorrow,",
        "never far from home,",
        "let there be light,",
        "from my end of the fibre optic cable to yours,",
        "in this together,",
        "sent from the stars,",
        "also also also and and and,",
        "nothing new,",
        "at my band's width,",
        "heck if i know,",
        "we're different but the same,",
        "no questions asked,",
        "i know the end,",
        "both out of habit and necessity,",
        "fondly,",
        "from memory,",
        "part of the process,",
        "rest in peace,",
        "heroically,",
        "bottom text,",
        "from the molecules of my being,",
        "typing off,",
        "as the edges crumble,",
        "today we do better,",
        "fingers crossed,",
        "controversially,",
        "keep it crispy,",
        "i want to see what happens next,",
        "not a lot just forever,",
        "your wish is my command,",
        "effective immediately,",
        "in time,",
        "spontaneously combusting,",
        "dazed and confused,",
        "at my best,",
        "dematerializing,",
        "falling back to earth,",
        "from the top of my heart,",
        "back to our regularly scheduled programming,",
        "it doesn't matter if you don't know the lingo,",
        "we ride at dawn,",
        "sending bright light,",
        "in beautiful company,",
        "with love and tremendous worry,",
        "solidarity forever,",
        "see you on the other side,",
        "in perpetuity,",
        "give and take care,",
        "dream well,",
        "allegedly,",
        "more to come,",
        "to hell with it,",
        "(sent with lasers),",
        "from my screen to yours,",
        "stressfully yours,",
        "get it twisted,",
        "all the best through the server from the heart,",
        "death to the enemy,",
        "ad astra,",
        "indefinitely,",
        "ashes to ashes,",
        "dust to dust,",
        "all things considered,",
        "no hard feelings,",
        "charmed,",
        "see you online,",
        "over and out,",
        "kind wishes from the HQ,",
        "we're different but the same,",
        "it was the best of times it was the worst of times, and no one knows about nuance,",
        "part of the process,",
        "this isn't even my final form,",
        "may thy knife chip and shatter,",
        "don't let the bastards get you down,",
        "tiocfaidh ár lá,",
        "salad is mostly items,",
        "may all kinds of shit happen,",
        "history will absolve me,",
        "with nuance,",
        "break me into bigger pieces,",
        "no one ever knows what you're talking about,",
        "per my last desperate howl at the heavens,",
        "i hope this email kills us both,",
        "take it,",
        "from every angle,",
        "one more time,",
        "human after all,",
        "hair to hair,",
        "sphere to square,",
        "something beautiful is going to happen,",
        "this is how we win,",
        "no solace but heat death,",
        "there is a choice and we will not make it,",
    ];

    return footers[Math.floor((Math.random() * footers.length))];
}
document.getElementById('footerText').innerHTML = footerText();

